EXPERIMENT_DIR: "lctgen-extended"
EXPERIMENT_NAME: "base-refiner-v0"

SAVE_CHECKPOINT: True
DEBUG: False
SEED: 0
GPU: []

MAX_EPOCHES: 10
LOG_INTERVAL_STEPS: 1
VAL_INTERVAL: 1
LIMIT_VAL_BATCHES: 1.0

MODEL:
  TYPE: lctgen

  MOTION:
    ENABLE: true
    STEP: 49
    CUMSUM: true
    PRED_MODE: mlp_gmm
    CLS_WEIGHT: 0.1
    K: 12
    PRED_HEADING_VEL: true

  PREDICT_EGO: true
  SCENE:
    EMBEDDING_DIM: 256
    HIDDEN_DIMS: []
    INIT_CFG:
      hidden_dim: 256
      DECODER:
        DROPOUT: 0.1
        FF_DIM: 2048
        LANE_NUM: 384
        MAP_POS: none
        MLP_DIM: 512
        NHEAD: 4
        NLAYER: 1
        QUERY_NUM: 32
        TYPE: agent_decode
        ATTR_GMM_ENABLE: True
        ATTR_GMM_K: 5
  
      ATTR_QUERY:
        POS_ENCODING_DIM: 256
DATASET:
  CACHE: False
  ENABLE_OUT_RANGE_TRAJ: True
  TYPE: WaymoOpenMotion
  MAX_TIME_STEP: 50
  TIME_SAMPLE_GAP: 1
  AUGMENTATION:
    ENABLE: true
    RANDOM_MASK_RATE: 0.1
  TRAJ_TYPE: xy_theta_relative
  DATA_LIST:
    TEST: val.txt
    VAL: val.txt
    TRAIN: train.txt
  TEXT:
    TYPE: attr_ind
    ALL_CLASSES:
    - 'pos'
    - 'distance'
    - 'direction'
    - 'speed'
    - 'action'
    CLASS:
    - 'pos'
    - 'distance'
    - 'direction'
    - 'speed'
    - 'action'
    NEGATIVE_SAMPLE_NUM: 10
    COUNT_BASE: 1
    DISTANCE_BASE: 20
    SPEED_BASE: 2.5
    USE_PADDING: True
    PADDING: -1
    FLATTEN: False
    USE_TRAJ: True
    ACTION_STEP: 4

TEST:
  BATCH_SIZE: 16
  SHUFFLE: false
  NUM_WORKERS: 4
  DATASET_PATH: ../data/query_structured_rep.json
TRAIN:
  BATCH_SIZE: 64
  LR: 0.0003
  OPTIMIZER: AdamW
  SCHEDULER:
    MILESTONES:
    - 70
    - 90
  NUM_WORKERS: 4
  DATASET_PATH: ../data/query_structured_rep.json
VAL:
  BATCH_SIZE: 16
  NUM_WORKERS: 4
  DATASET_PATH: ../data/query_structured_rep.json
